//enemy a package discribing the properties of an enemy
package main

//Enemy describes an enemy combatant
type Enemy struct {
	//Name will be autogenerated from various possibilities
	Name string
	ID   string
	Race int
	Cast int
	//Items which the player can loot
	Items []Item
	//Gold which the player can loot
	Gold int
	//Xp is calculated based on level and rareness
	Xp    int
	Level int
	//RarenessLevel is 1-10 where 10 is highly rare
	RarenessLevel int
}
